version: '3.8'

services:

  postgres_db:
    image: postgres:15
    container_name: fitpersona_db
    restart: always
    environment:
      POSTGRES_DB: fitpersona
      POSTGRES_USER: fitatuser
      POSTGRES_PASSWORD: fitpassword123
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: fitpersona_backend
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/fitpersona
      SPRING_DATASOURCE_USERNAME: fitatuser
      SPRING_DATASOURCE_PASSWORD: fitpassword123
    depends_on:
      - postgres_db

  frontend:
    build: .
    container_name: fitpersona_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
  volumes:
    - /etc/letsencrypt:/etc/letsencrypt

# volumes:
#   fitpersona_data:
