version: '3.8'

services:

  postgres_db:
    image: postgres:15
    container_name: fitpersona_db
    restart: always
    environment:
      POSTGRES_DB: fitpersona
      POSTGRES_USER: fitpersona_user
      POSTGRES_PASSWORD: fitpersona_pass
    volumes:
      - fitpersona_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: fitpersona_backend
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/fitpersona
      SPRING_DATASOURCE_USERNAME: fitpersona_user
      SPRING_DATASOURCE_PASSWORD: fitpersona_pass
    depends_on:
      - postgres_db

  frontend:
    build: ./frontend
    container_name: fitpersona_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  fitpersona_data: